Web/Controllers/HomeController.cs
using System.Web.Mvc;
using WarehouseLaborEfficiencyWeb.DAL;

namespace WarehouseLaborEfficiencyWeb.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return RedirectToAction("WeekData");
        }
        
        #region Page
        public ActionResult WeekData()
        {
            if (!CommonInfo.IsLogin())
            {
                return RedirectToAction("Signin", "Login");
            }
            return View();
        }
        public ActionResult MonthData()
        {
            if (!CommonInfo.IsLogin())
            {
                return RedirectToAction("Signin", "Login");
            }
            return View();
        }
        public ActionResult HCData()
        {
            if (!CommonInfo.IsLogin())
            {
                return RedirectToAction("Signin", "Login");
            }
            return View();
        }

        public ActionResult HCRate()
        {
            if (!CommonInfo.IsLogin())
            {
                return RedirectToAction("Signin", "Login");
            }
            return View();
        }
        #endregion

        #region 数据编辑
        [HttpGet]
        public ActionResult ModifyData(string dataType)
        {
            switch (dataType)
            {
                case "WeekData":
                    return RedirectToAction("ModifyWeekData");
                case "MonthData":
                    return RedirectToAction("ModifyMonthData");
                case "HCData":
                    return RedirectToAction("ModifyHCData");
                default:break;
            }
            return new HttpNotFoundResult();
        }

        [HttpGet]
        public ActionResult ModifyWeekData()
        {
            if (!CommonInfo.HasRight(TRightID.MODIFY))
            {
                return new HttpUnauthorizedResult("没有权限！");
            }            
            return View();
        }
        [HttpGet]
        public ActionResult ModifyMonthData()
        {
            if (!CommonInfo.HasRight(TRightID.MODIFY))
            {
                return new HttpUnauthorizedResult("没有权限！"); 
            }
            return View();
        }
        [HttpGet]
        public ActionResult ModifyHCData()
        {
            if (!CommonInfo.HasRight(TRightID.MODIFY))
            {
                return new HttpUnauthorizedResult("没有权限！");
            }
            return View();
        }
        #endregion
    }
}

Web/Controllers/QueryController.cs
using Common.DotNetCode;
using Common.DotNetExcel;
using System;
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;
using WarehouseLaborEfficiencyBLL;
using WarehouseLaborEfficiencyWeb.DAL;

namespace WarehouseLaborEfficiencyWeb.Controllers
{
    public class QueryController : Controller
    {
        private string GetTempDirBase()
        {
            var spath = HttpContext.Server.MapPath("~/temp"); ;
            if (!System.IO.Directory.Exists(spath))
            {
                System.IO.Directory.CreateDirectory(spath);
            }
            return spath;
        }

        public ActionResult GetWarehouseInfo()
        {
            var lstData = QueryHelper.GetWarehouseList();
            var obj = new TRes
            {
                bok = true,
                data = lstData
            };

            if (null == lstData || 0 == lstData.Count)
            {
                obj.bok = false;
                obj.msg = "没有查询到数据";
            }
            return Json(obj);
        }

        #region WeekData        
        [HttpPost]
        public ActionResult QueryYear(string dataType)
        {
            var warehouses = QueryHelper.GetWarehouseList();
            var lstData = QueryHelper.QueryYear(dataType);
            var obj = new TRes
            {
                bok = true,
                data = lstData,
                extra= warehouses
            };

            if (null == lstData || 0 == lstData.Count)
            {
                obj.bok = false;
                obj.msg = "没有查询到数据";
            }
            return Json(obj);
        }

        [HttpPost]
        public ActionResult GetWeekDataInitInfo(string selYear)
        {
            var lstData = QueryHelper.GetWeekdateList(selYear);
            var obj = new TRes
            {
                bok = true,
                data = lstData
            };            

            if (null==lstData || 0 == lstData.Count)
            {
                obj.bok = false;
                obj.msg = "没有查询到数据";
            }
            return Json(obj);
        }

        [HttpPost]
        public ActionResult QueryWeekData(string bu, string startDate, string endDate)
        {
            var obj = new TRes
            {
                bok = true
            };

            try
            {
                var datWeek = QueryHelper.GetWeekData(bu, startDate, endDate);
                obj.data = datWeek;
                if (null == datWeek.data || 0 == datWeek.columns.Count)
                {
                    obj.bok = false;
                    obj.msg = "没有查询到数据";
                }
            }
            catch (Exception ex)
            {
                obj.bok = false;
                obj.msg = "数据有问题:" + ex.Message;
            }

            return Json(obj);
        }

        [HttpPost]
        public ActionResult QueryWeekDataAll(string date, string warehouse)
        {
            var obj = new TRes
            {
                bok = true
            };

            try
            {
                var datWeek = QueryHelper.QueryWeekDataAll(date, warehouse);
                obj.data = datWeek;
                //if (0 == datWeek.Count)
                //{
                //    obj.bok = false;
                //    obj.msg = "没有查询到数据";
                //}
            }
            catch (Exception ex)
            {
                obj.bok = false;
                obj.msg = "数据有问题:" + ex.Message;
            }

            return Json(obj);
        }
        #endregion

        #region Month Data
        [HttpPost]
        public ActionResult GetMonthDataInitInfo()
        {
            var lstData = QueryHelper.GetWarehouseList();
            var obj = new TRes
            {
                bok = true,
                data = lstData,
                extra = QueryHelper.GetMonthdateList(),
            };

            if (null == lstData || 0 == lstData.Count)
            {
                obj.bok = false;
                obj.msg = "没有查询到数据";
            }
            return Json(obj);
        }

        [HttpPost]
        public ActionResult QueryMonthData(int selYear, string selKind)
        {
            var dat = QueryHelper.GetMonthData(selYear, selKind);
            var obj = new TRes
            {
                bok = true,
                data = dat
            };
            if (null == dat.data || 0 == dat.columns.Count)
            {
                obj.bok = false;
                obj.msg = "没有查询到数据";
            }
            return Json(obj);
        }

        [HttpPost]
        public ActionResult QueryMonthDataAll(string date, string warehouse)
        {
            var obj = new TRes
            {
                bok = true
            };

            try
            {
                var dat = QueryHelper.QueryMonthDataAll(date, warehouse);
                obj.data = dat;
                //if (0 == datWeek.Count)
                //{
                //    obj.bok = false;
                //    obj.msg = "没有查询到数据";
                //}
            }
            catch (Exception ex)
            {
                obj.bok = false;
                obj.msg = "数据有问题:" + ex.Message;
            }

            return Json(obj);
        }
        #endregion

        #region HCData        
        [HttpPost]
        public ActionResult QueryHCData(string selYear, string warehouses)
        {
            var dat = QueryHelper.GetHCData(selYear, warehouses);
            var obj = new TRes
            {
                bok = true,
                data = dat
            };

            if (0==dat.Count)
            {
                obj.bok = false;
                obj.msg = "没有查询到数据";
            }
            return Json(obj);
        }

        [HttpPost]
        public ActionResult QueryHCDataAll(string date, string warehouse)
        {
            var obj = new TRes
            {
                bok = true
            };

            try
            {
                var dat = QueryHelper.QueryHCDataAll(date, warehouse);
                obj.data = dat;
                //if (0 == datWeek.Count)
                //{
                //    obj.bok = false;
                //    obj.msg = "没有查询到数据";
                //}
            }
            catch (Exception ex)
            {
                obj.bok = false;
                obj.msg = "数据有问题:" + ex.Message;
            }

            return Json(obj);
        }
        
        #endregion

        #region HCRate
        [HttpPost]
        public ActionResult GetHCRateMonth(string selYear)
        {
            var lstData = QueryHelper.GetHCRateMonth(selYear);
            var obj = new TRes
            {
                bok = true,
                data = lstData
            };

            if (null == lstData || 0 == lstData.Count)
            {
                obj.bok = false;
                obj.msg = "没有查询到数据";
            }
            return Json(obj);
        }

        [HttpPost]
        public ActionResult QueryHCRate(string selMonth, string warehouses)
        {
            var dat = QueryHelper.QueryHCRate(selMonth, warehouses);
            var obj = new TRes
            {
                bok = true,
                data = dat
            };

            if (0 == dat.Count)
            {
                obj.bok = false;
                obj.msg = "没有查询到数据";
            }
            return Json(obj);
        }
        #endregion

        [HttpPost]
        public ActionResult UploadData(string dataType, HttpPostedFileBase file)
        {
            var res = new TRes
            {
                bok = false,
                msg = ""
            };
            if (!ModelState.IsValid)
            {
                res.msg = "数据无效";
                ModelState.AddModelError("", res.msg);
                return Json(res, JsonRequestBehavior.AllowGet);
            }
            if (!CommonInfo.HasRight(TRightID.UPLOAD))
            {
                res.msg = "没有上传权限";
                ModelState.AddModelError("", res.msg);
                return Json(res, JsonRequestBehavior.AllowGet);
            }
            if (string.IsNullOrEmpty(dataType))
            {
                res.msg = "请选择数据类型";
                ModelState.AddModelError("", res.msg);
                return Json(res, JsonRequestBehavior.AllowGet);
            }
            if (file == null || file.ContentLength == 0)
            {
                res.msg = "文件有问题";
                ModelState.AddModelError("", res.msg);
                return Json(res, JsonRequestBehavior.AllowGet);
            }

            var sErrImp = string.Empty;
            bool bImp = BLLHelper.ImpUpload(dataType, file, out sErrImp);
            res.bok = bImp;
            if (!bImp)
            {
                res.msg = sErrImp;
                ModelState.AddModelError("", res.msg);
            }
            return Json(res, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public ActionResult DownloadData(string dType, string bu, string startWeek, string endWeek, string selYear)
        {
            if (!CommonInfo.HasRight(TRightID.DOWNLOAD))
            {
                return new HttpUnauthorizedResult();
            }
            switch (dType)
            {
                case "WeekData":
                    return DownloadData_WeekData(bu, startWeek, endWeek);
                //case "MonthData":
                //    return DownloadData_MonthData(bu, startWeek, endWeek);
                case "HCData":
                    return DownloadData_HCData(bu, selYear);
            }
            return new EmptyResult();
        }

        [HttpGet]
        public ActionResult DownloadMonthData(string selKind)
        {
            if (!CommonInfo.HasRight(TRightID.DOWNLOAD))
            {
                return new HttpUnauthorizedResult();
            }
            var fn = string.Format("{0}_{1}.xlsx", "MonthData", selKind);

Web/Views/Home/HCData.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using WarehouseLaborEfficiencyWeb.DAL


@section Styles{
<style>
.myUl {
    list-style: none;
    padding: 0;
    margin: 0;
    font-size: 11px;
}
.myUl li { 
    padding-left: 16px; 
    line-height: 16px;
}
    .myUl li::before {
        content: "•";
        vertical-align:middle;
        padding-right: 8px;
        color: green;
        font-size: 24px;
        font-weight: 700;
    }
</style>
}
<div class="row InfoHead">
    <div class="col-md-9">
        <h3>
            Headcount Position Distribution Monthly Trend
        </h3>
    </div>
</div>


<div class="wrapper">
    @using (Html.BeginForm("QueryHCData", "Query",
                                   FormMethod.Post, new { @id = "frmQueryHCData" }))
    {
        <div class="row">
            <div class="col-md-7">
                <span class="my-bigger">WareHouse</span>
                <span>
                    <select id="idSelBu" required multiple>
                        @*<option></option>*@
                    </select>
                    @Html.Hidden("warehouses")
                </span>
            </div>
            <div class="col-md-2">
                <span class="my-bigger">Year</span>
                <span>
                    <select id="idSelYear" name="selYear" required>
                        <option></option>
                    </select>
                </span>
            </div>
            <div class="col-md-3">
                @Html.ValidationSummary(false, "", new { @class = "text-danger" })
                <button class="btn btn-info btn-sm" type="submit" id="btnQuery">Query</button>
                <button class="btn btn-info btn-sm" type="button" id="btnQueryAll">Query All</button>
                @if (CommonInfo.HasRight(TRightID.DOWNLOAD))
                {
                    <button class="btn btn-info btn-sm" type="button" id="btnDownload">Download</button>
                }
            </div>
        </div>
    }
</div>

<div class="container" id="idChartCont" style="width: 1200px;margin-left: -40px;">
</div>



@section Scripts{
    <script>
        var selectorYear = null;

        $(function () {
            InitData();
            InitSelYear();
            setTimeout(function () {
                DoQueryAll();
            }, 800);
            VisitTrack('WarehouseLaborEfficiencyDashboard', 'HCData', '');
        });

        function InitData() {
            $("#frmQueryHCData").validate();
            $("#btnDownload").click(function () {
                DownloadData('HCData', $("#frmQueryHCData"));
            });
            $("#btnQueryAll").click(function () {
                DoQueryAll();
            });

            selectorYear = new TSelect2Helper($("#idSelYear"));
            //selectorYear.SetSelectChangeCallback(RefSelYear);

            var url = "@Url.Action("GetWarehouseInfo", "Query")";
            AjaxPost(url,
                "{}",
                true,
                function (result) {
                    var warehouseList = result.data || [];
                    $("#idSelBu").select2({
                        data: warehouseList,
                        placeholder: "choose one or more warehouse...",
                        width: "70%"
                    });

                });

            $('#frmQueryHCData').on('submit', function (e) {
                if (e.isDefaultPrevented()) {
                    //invalid
                    return false;
                } else {
                    var url = $(this).attr("action");
                    $('#warehouses').val(GetSelect2SelMulti($('#idSelBu')));
                    AjaxPostForm(url, '#frmQueryHCData', true, function (resp) {
                        if (resp.bok) {
                            ViewCharts(resp.data);
                        } else {
                            BootstrapDialog.alert("查询失败:<br>" + resp.msg);
                        }
                    },
                    undefined,
                    function () {
                        showBusyLoading(true);
                    },
                    function () {
                        showBusyLoading(false);
                    });
                }
                return false;
            });
        }


        function InitSelYear() {
            var url = "@Url.Action("QueryYear", "Query")";
            var para = {
                dataType: "HCData"
            };
            AjaxPost(url,
                JSON.stringify(para),
                true,
                function (result) {
                    if (!result.bok) {
                        BootstrapDialog.alert(result.msg);
                        return;
                    }
                    var yearList = result.data || [];
                    //var warehouseList = result.extra || [];

                    $("#idSelYear").select2({
                        data: yearList,
                        placeholder: "choose...",
                        width: "120px"
                    });
                });
        }
        function DoQueryAll() {
            var $ctlSelBu = $('#idSelBu');
            $ctlSelBu.find('option').prop('selected', 'selected');
            $ctlSelBu.trigger('change');
            $("#btnQuery").click();
        }
        function CreateAChart(name) {
            var chartHead = '<div class="wrapper" style="margin-top:18px;">';
            var chartBegin = '<div class="row"><div id="idChart_';
            var chartEnd = '" style="height:520px;"></div></div>';
            var chartDesc = '<div class="row">'
                                + '<ul class="myUl">'
                                + '<li>Total = System Clerk+Receiving+Shipping+RTV & Scrap+Inventory Control+Overall.</li>'
                                + '<li>Forklift Driver included in the Receiving and Shipping.</li>'
                                + '</ul>'
                            +'</div>';
            var charTail = '</div>';
            return chartHead + chartBegin + name + chartEnd + chartDesc + charTail;
        }
        function ViewCharts(items) {
            if (!items || 0 == items.Length) {
                return;
            }
            var $cont = $('#idChartCont');
            $cont.empty();
            //chartHead += name;
            $.each(items, function (ind, val) {
                var name = val.name;
                $cont.append(CreateAChart(name));
            });

            $.each(items, function (ind, val) {
                RefreshChart(val.name, val.entry);
            });
        }

        function GetBarColors() {
            return [
                '#5499C7', '#2980B9', '#2471A3',
                '#1F618D', '#1A5276', '#154360'
            ];
            //return [
            //    '#5499C7', '#2980B9', '#2471A3',
            //    '#1F618D', '#1A5276', '#154360',
            //    '#0033FF', '#0033CC', '#003399',
            //    '#003366', '#003333', '#003300'
            //];
            //return ['#5D9EDB', '#F57E2F', '#A5A5A5',
            //        '#FFC60E', '#4373CA', '#6BAD3E',
            //        '#FF00CC', '#DD6633', 'purple',
            //        '#330099', '#FFEE00', '#CCCC66',
            //        '#9999FF'
            //];
        }
        function MakexAxis(cols) {
            var xCols = [];
            $.each(cols, function (index, value) {
                var tVal = value.data;
                xCols.push(value.data);
            });
            return xCols.slice(1);
        }
        function MakeChartData(itemData) {
            var chartData = [];
            var cols = [];
            var details = itemData.data;
            var labelOption = {
                normal: {
                    show: true,
                    position: 'top',
                    distance: 15,
                    verticalAlign: 'middle',
                    rotate: 90,
                    fontSize: 9,
                    formatter: function (ser) {
                        if (!ser.data) {
                            return '';
                        }
                        return ser.data;
                    }
                }
            };

            $.each(details, function (index, value) {
                var vArr = MakeValueArr(value);
                var item = vArr[0];
                cols.push(item)
                var objChart = {
                    'name': item,
                    'type': 'bar',
                    'barGap': '0',
                    'data': vArr.slice(1),
                    'label': labelOption
                };
                chartData.push(objChart);
            });
            return {
                'cols': cols,
                'kinds': itemData.kinds,
                'charData': chartData
            }
        }
        function RefreshChart(name, itemData) {
            var cd = MakeChartData(itemData);
            //var xCols = MakexAxis(cd.cols);
            var option = {
                tooltip: {
                    trigger: 'axis',
                    axisPointer: {
                        type: 'shadow'
                    }
                },
                color: GetBarColors(),
                title: {
                    text: name + " (G1-G7)",
                    textStyle:{
                        fontSize:16
                    },
                    left: 'center'
                },
                legend: {
                    data: cd.cols,
                    right: '20px',
                    align: 'right',
                    orient: 'vertical',
                    x: 'right', y: 'center',
                    textStyle: {
                        fontWeight: 'bold'
                    }
                },
                grid: {
                    left: '0%',
                    right: '9.5%',
                    bottom: '2%',
                    containLabel: true
                },
                xAxis: [
                    {
                        type: 'category',
                        data: cd.kinds
                    }
                ],
                yAxis: [
                    {
                        type: 'value'
                    }
                ],
                series: cd.charData
            };

            var weekChart = echarts.init(document.getElementById("idChart_"+name));
            weekChart.setOption(option);

        }

    </script>
}

Web/Views/Home/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <style type="text/css">
        #tbList {
            border:1px solid #0094ff;
            width:800px;
            margin:10px auto;
            border-collapse:collapse;
        }
        #tbList th, td {
            border:1px solid #0094ff;
            padding:10px;
        }
    </style>
    <script type="text/javascript">

    </script>
</head>
<body>
    
</body>
</html>

Web/Views/Home/ModifyHCData.cshtml
@using WarehouseLaborEfficiencyWeb.DAL;

@{
    ViewBag.Title = "ModifyHCData";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Styles.Render("~/Content/jsgrid")
@Scripts.Render("~/bundles/jsgrid")


@section Scripts{
    <script>
        var gridHelper = null;
        function DeleteItems(items) {
            var url = "@Url.Action("DeleteHCData", "Query")";
            var ids = [];
            items.forEach(function (it) {
                ids.push(it.id);
            });
            var para = { ids: ids};
            AjaxPost(url,
                JSON.stringify(para),
                true,
                function (result) {
                    if (!result.bok) {
                        BootstrapDialog.alert(result.msg);
                        return;
                    } else {
                        reloadRaw();
                        //gridHelper.refresh();
                    }
                });
        }

        $(function () {
            gridHelper = new GridHelper("#gridHCData");
            var warehouses = gridHelper.Warehouses.slice(0);
            warehouses.unshift({ name: "All", value: "" });
            var $gridHCData = $("#gridHCData").jsGrid({
                height: "auto",
                width: "100%",
                inserting: false,
                editing: false,
                sorting: true,
                filtering: true,
                paging: true,
                pageSize: 15,
                pageButtonCount: 5,
                autoload: true,
                controller: {
                    loadData: function(filter) {
                        var d = $.Deferred();
                        var surl = "@Url.Action("QueryHCDataAll", "Query")";
                        var para = {};
                        if (null != filter) {
                            para.Date = filter.Date;
                            para.Warehouse = filter.Warehouse;
                        }
                        AjaxPost(surl,
                            JSON.stringify(para),
                            true,
                            function (resp) {
                                var dat = resp.data;
                                d.resolve(dat);
                            });
                        return d.promise();
                    }
                },
                fields: [
                    {
                        headerTemplate: function () {
                            return $("<button>").attr("type", "button").text("Delete").addClass("btn btn-danger btn-sm")
                                    .on("click", function () {
                                        if (!gridHelper.hasSelected()) {
                                            BootstrapDialog.alert("没有选择记录!");
                                            return;
                                        }
                                        BootstrapDialog.confirm("确定要永久删除所选记录吗?", function (result) {
                                            if (!result) {
                                                return;
                                            }
                                            gridHelper.deleteSelectedItems(DeleteItems);
                                        });
                                    });
                        },
                        itemTemplate: function (_, item) {
                            return $("<input>").attr("type", "checkbox")
                                    .prop("checked", $.inArray(item, gridHelper.selectedItems) > -1)
                                    .on("change", function () {
                                        $(this).is(":checked") ? gridHelper.selectItem(item) : gridHelper.unselectItem(item);
                                    });
                        },
                        align: "center",
                        width: 80
                    },
                    { name: "id", type: "number", readOnly: true, filtering: false, visible:false},
                    { name: "Date", type: "text", width:100 },
                    { name: "Warehouse", type: "select", items: warehouses, textField: "name", valueField: "value", selectedIndex:-1, width:100},
                    { name: "Overall", type: "number", readOnly: true, filtering: false },
                    { name: "System_Clerk", type: "number", readOnly: true, filtering: false },
                    { name: "Inventory_Control", type: "number", readOnly: true, filtering: false,width:140},
                    { name: "RTV_Scrap", type: "number", readOnly: true, filtering: false },
                    { name: "Receiving", type: "number", readOnly: true, filtering: false },
                    { name: "Shipping", type: "number", readOnly: true, filtering: false },
                    { name: "Forklift_Driver", type: "number", readOnly: true, filtering: false },
                    { name: "Total", type: "number", readOnly: true, filtering: false }
                ]
            });
        });

    </script>
}

<div class="row InfoHead">
    <div class="col-md-9">
        <h3>
            Modify HCData
        </h3>
    </div>
</div>

<div class="wrapper">
    <div class="panel panel-default">
        <div class="panel-body">
            <div id="gridHCData"></div>
        </div>
    </div>

</div>